name: CI

on:
  pull_request:
    branches: [ main ]          # CI on PRs → main (must-have) 
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * *"         # daily 07:00 UTC run (nice-to-have)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Lint (black check)
        run: black --check .

      - name: Lint (flake8)
        run: flake8 .

      - name: Security scan (bandit)
        continue-on-error: true     # nice-to-have; don’t fail exercise on warnings
        run: bandit -r app -x tests

      - name: Tests (pytest + coverage)
        run: |
          pytest -q --cov=app --cov-report=xml --junitxml=pytest-results.xml

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            coverage.xml
            pytest-results.xml
