name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev, qa ]
  workflow_dispatch: {}   # gives the "Run workflow" button

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          # if you have it:
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Black (format check)
        run: black --check .

      - name: Flake8 (lint)
        run: flake8 .

      - name: Bandit (security)
        run: bandit -r app tests -c bandit.yaml -q

      - name: Pytest (+coverage)
        env:
          PYTHONPATH: .
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
